### ISSUE TITLE
In spetral clustering do u know how to choose the best gamma?

### ISSUE THREAD

**Issue by StevenIIV** [duducheng/clustering#1]

**Comment by duducheng** [comment]
Hi @StevenIIV,

Sorry to disappoint you, but it is out of scope of this repo. It is aimed at a implementation tutorial. Please refer to the original paper for some discussion. In general, cross validation is always useful if you could define what metrics should be used on your dataset. In principle, there is no free lunch in machine learning; everything is about your data.
